
### Get Episodes ###
POST http://localhost:3000/api/episodes HTTP/1.1


### Sync Tracks

POST http://localhost:3000/api/internal/sync-episodes HTTP/1.1

### Get episodes

GET http://localhost:3000/api/trpc/episodes.all HTTP/1.1

### Sync Episodes Old
GET http://localhost:3000/api/trpc/internal.episodesSync


### Sync Episodes New
GET http://localhost:3000/api/trpc/internal.episodesSyncNew

### Get Stream URLS
GET http://localhost:3000/api/trpc/episode.getStreamUrl?input=%7B%22episodeId%22%3A%22624632f8ccc079804723e07b%22%7D HTTP/1.1


### Get soundcloud api token
# @name gatAccessToken
POST http://api.soundcloud.com/oauth2/token?client_id={{SOUNDCLOUD_CLIENT_ID}}&client_secret={{SOUNDCLOUD_CLIENT_SECRET}}&grant_type=client_credentials HTTP/1.1


### Backfill collective (Requires Auth)
GET http://localhost:3000/api/trpc/internal.backfillCollectives
Authorization: Basic dGhlYm95YW5kdGhla2l0dGVuc3llcDptb3NoaXRoZWNhdA==

### Test Auth (Requires Auth)
GET http://localhost:3000/api/trpc/internal.testAuth
Authorization: Basic dGhlYm95YW5kdGhla2l0dGVuc3llcDptb3NoaXRoZWNhdA==

### Import Episode Track Info (Requires Auth)
POST http://localhost:3000/api/trpc/internal.importEpisodeTrackInfo
Authorization: Basic dGhlYm95YW5kdGhla2l0dGVuc3llcDptb3NoaXRoZWNhdA==
Content-Type: application/json

{
  "streaming_urls": {
    "soundcloud_url": "https://soundcloud.com/soulection/show-700-uptempo-edits-timeless-soul",
    "apple_music_url": "https://music.apple.com/us/station/episode-700/ra.1837450757"
  },
  "tracks": [
    {
      "track_number": 1,
      "timestamp": "00:00:20",
      "artist": "Afrikano",
      "song": "Jazzapiano",
    },
  ]
}

### Get soundcloud tracks

@SOUNDCLOUD_API_TOKEN = {{gatAccessToken.response.body.access_token}}

# @name getPlaylistDetails
GET http://api.soundcloud.com/playlists/944232886 HTTP/1.1
Authorization: OAuth {{SOUNDCLOUD_API_TOKEN}}


### Get single track details
GET http://api.soundcloud.com/tracks/974975893 HTTP/1.1
Authorization: OAuth {{SOUNDCLOUD_API_TOKEN}}

### Get Stream Url
GET https://api.soundcloud.com/tracks/159482763/streams
Authorization: OAuth {{SOUNDCLOUD_API_TOKEN}}

### Dwnload Track
  GET https://api.soundcloud.com/tracks/159482763/download
Authorization: OAuth {{SOUNDCLOUD_API_TOKEN}}


# Test trackId ra.1212031753
### Apple Music Get Track
GET https://api.music.apple.com/v1/catalog/us/songs/ra.1212031753

# Authentication Notes:
# - Replace "dXNlcm5hbWU6cGFzc3dvcmQ=" with base64 encoded "username:password"
# - Set INTERNAL_AUTH_USERNAME and INTERNAL_AUTH_PASSWORD in your .env file
# - Example: echo -n "myuser:mypass" | base64



# Sync Episodes TRPC
# {
#   "id": null,
#   "result": {
#     "type": "data",
#     "data": {
#       "msg": "Successfully Fetched New Tracks",
#       "retrievedTracks": [
#         "Soulection Radio Show #542 (Live from 1015 Folsom, San Francisco)",
#         "Soulection Radio Show #541",
#         "Soulection Radio Show #540",
#         "Soulection Radio Show #539",
#         "Soulection Radio Show #538 ft. Budgie (A Lover's Special)",
#         "Soulection Radio Show #537",
#         "Soulection Radio Show #536",
#         "Soulection Radio Show #535",
#         "Soulection Radio Show #534",
#         "Soulection Radio Show #533 (Rich Medina Takeover)",
#         "Soulection Radio Show #532 (Andre Power Takeover)"
#       ]
#     }
#   }
# }
